### PR TITLE
Getting all the new stuff..

### PR DESCRIPTION
**Pull request by brynawesomehd321**
Okay so I got the update before this one, but it gave almost every class have an error. Do you guys know what happened, because I cant do anything with these errors.

### CODE REVIEW

**Comment by GoldenPigFlynn** [comment]
Hi Bryn:

I believe you need to upgrade your forge version? 

What are the error messages that you see?
- bri

**Comment by brynawesomehd321** [comment]
I'm seeing errors in the code for almost every single class. Especially in bigger classes like base item and base block

**Comment by brynawesomehd321** [comment]
What forge version should I get? The latest?

**Comment by michaelconnolly** [comment]
Bryn, check out the latest steps!  Are you around this week?  Maybe I should help you get your laptop updated.

**Comment by brynawesomehd321** [comment]
We are going to be out of cell coverage all week because we are going backpacking, but maybe after that? I'm not sure what's going on that week.

**Pull request merged**
